name: Build and Test with Secrets

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Check if secret is available
        run: |
          if [ "${{ secrets.MY_GITHUB_SECRET }}" == "" ]; then
            echo "WARNING: MY_GITHUB_SECRET is not set in repository secrets!"
            echo "Please add it in repository settings: Settings -> Secrets and variables -> Actions"
          else
            echo "MY_GITHUB_SECRET is available for use"
          fi

      - name: Run Spring Boot App with Secret
        env:
          MY_GITHUB_SECRET: ${{ secrets.MY_GITHUB_SECRET }}
        run: |
          echo "Starting application with MY_GITHUB_SECRET environment variable..."
          java -jar target/test-0.0.1-SNAPSHOT.jar > app_output.log 2>&1 &
          APP_PID=$!
          echo "Application started with PID: $APP_PID"
          
          # Give the app some time to start
          echo "Waiting for application to start..."
          sleep 10
          
          # Display application output
          echo "Application startup log:"
          cat app_output.log
          
          # Test the endpoint
          echo "Testing endpoints..."
          
          ROOT_ENDPOINT=$(curl -s http://localhost:8080/)
          echo "Root endpoint response: $ROOT_ENDPOINT"
          
          CHECK_SECRET=$(curl -s http://localhost:8080/check-secret)
          echo "Check secret endpoint response: $CHECK_SECRET"
          
          ENV_ENDPOINT=$(curl -s http://localhost:8080/env)
          echo "Environment endpoint response: $ENV_ENDPOINT"
          
          # Clean up
          kill $APP_PID || true