name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Run Spring Boot App with Secret
      env:
        # This passes the GitHub secret to the application as an environment variable
        MY_GITHUB_SECRET: ${{ secrets.MY_GITHUB_SECRET }}
      run: java -jar target/secrets-demo-0.0.1-SNAPSHOT.jar &
      
    - name: Wait for application to start
      run: sleep 10
      
    - name: Verify secret is available
      run: |
        response=$(curl -s http://localhost:8080/check-secret)
        echo "Response: $response"
        if [[ "$response" == *"not configured"* ]]; then
          echo "Secret not properly configured"
          exit 1
        fi
